apiVersion: v1
kind: Service
metadata:
  name: kubernetes-exploration-service
spec:
  selector:
    app: kubernetes-exploration
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-exploration
spec:
  selector:
    matchLabels:
      app: kubernetes-exploration
  replicas: 4
  template:
    metadata:
      labels:
        app: kubernetes-exploration
    spec:
      containers:
      - name: kubernetes-exploration
        image: kubernetes-exploration:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000